name: Deploy Uffizzi Previews

on:
  workflow_run:
    workflows:
      - Build Images
    types:
      - completed

jobs:
  cache-compose-file:
    name: Cache Compose File
    runs-on: ubuntu-latest
    outputs:
      compose-file-cache-key: ${{ steps.hash.outputs.hash }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: docker-compose
      - name: Hash Rendered Compose File
        id: hash
        run: echo "::set-output name=hash::$(md5sum docker-compose.rendered.yml | awk '{ print $1 }')"
      - name: Cache Rendered Compose File
        uses: actions/cache@v3
        with:
          path: docker-compose.rendered.yml
          key: ${{ steps.hash.outputs.hash }}

  deploy-uffizzi-preview:
    name: Use Remote Workflow to Preview on Uffizzi
    needs:
      - cache-compose-file
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2
    #if: ${{ github.event.workflow_run.event.action != 'closed' }}
    with:
      compose-file-cache-key: ${{ needs.cache-compose-file.outputs.compose-file-cache-key }}
      compose-file-cache-path: docker-compose.rendered.yml
      server: https://app.uffizzi.com/
    permissions:
      contents: read
      pull-requests: write
      id-token: write

#  delete-uffizzi-preview:
#    name: Use Remote Workflow to Delete an Existing Preview
#    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@v2
#    if: ${{ github.event.workflow_run.event.action == 'closed' }}
#    with:
#      compose-file-cache-key: ''
#      compose-file-cache-path: docker-compose.rendered.yml
#      server: https://app.uffizzi.com/
#    permissions:
#      contents: read
#      pull-requests: write
#      id-token: write
